repository: jiemo9527/jiemo9527.github.io
repository_url: https://github.com/jiemo9527/jiemo9527.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: Go导航
alias_en: go导航
alias_cn: go导航
description: go导航
keywords: 导航,门户,go
url: https://go.jie02.top
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor